### ISSUE TITLE
Mouse cursor not falling in place, when i am trying to edit

### ISSUE THREAD

**Issue by aahnik** [ceoshikhar/better-github#6]
I am a firefox user. I installed the extension from firefox add ons.

I had applied Fira Code and size 14.

Everything was heavenly until this happened.

When I am editing text in Github's editor, when the extension is enabled, the mouse cursor is not falling on place. If I click at  a place, the cursor is falling far away from it.

If I click reset in the extension, then font changes to normal, and the cursor bug goes away.

![image](https://user-images.githubusercontent.com/66209958/113476203-a8544680-9497-11eb-80ef-2b9500753f6d.png)

screenshot from [telewater](https://github.com/aahnik/telewater/)

**Comment by ceoshikhar** [comment]
Yeah, you are right. The cursor placement is inconsistent, sometimes it's at the right place sometimes it's not. This issue is also observed on Chrome as well. I would have picked up on this myself but I **never** edit files on GitHub. I will have to look into what is causing this to further investigate on this issue, till then you can do one of the followings : 
1. Don't use the extension, probably uninstall it if you edit a lot on GitHub.
2. Disable extension while editing files.

The main motivation behind creation of this project was for the reading purpose, I guess I will have to work on the **editing** part as well but it won't really be the most pressing matter for now, hence I gave you those two options.

Thanks for creating the issue and bringing it to my notice.

**Comment by ceoshikhar** [comment]
Can you make a small GIF demonstrating the issue? I would really appreciate it.

**Comment by aahnik** [comment]
i generally dont edit files on github. but for quick fixes in readme files or documentation, I do.

**Comment by aahnik** [comment]
![better-github-cursor-bug](https://user-images.githubusercontent.com/66209958/113477853-9c21b680-94a2-11eb-9e0a-0dc843bab82e.gif)

see where i am clicking (you will see a orange ripple there )and where is the cursor (blinking)

**Comment by aahnik** [comment]
one simple workaround is simply using arrow keys to navigate the text, instead of mouse

**Comment by aahnik** [comment]
hi @ceoshikhar did you find any solution to this problem?

**Comment by ceoshikhar** [comment]
@aahnik hey! I have been on a break for the whole time. I think I am back to grind. Will start working on both of these issues created by you as soon as tomorrow. I am pretty confident I know how I can fix both the issues 😉

**Comment by ceoshikhar** [comment]
@aahnik I have been looking into this and I have to say, the GitHub code editor does weird things if you change the font size or family of those code lines. I think the best for now would be to make it such that the extension won't fire off when someone is editing a file. By doing this, their code lines will have default settings while editing files. 

But I will keep looking into it and if in the long run I figure out why GitHub does this crazy thing with the cursor if the font styles are changed, I will add the feature. 

Sounds good?

**Comment by aahnik** [comment]
> I think the best for now would be to make it such that the extension won't fire off when someone is editing a file. By doing this, their code lines will have default settings while editing files.

Yup! I also thought of that. That's a fantastic fix.

I generally use Github's editor for small spelling fixes or adding a hyperlink to a word. When I am writing longer documents I use VS Code.

So, this fix would be perfect.

**Comment by ceoshikhar** [comment]
@aahnik The latest release is published on Firefox addon store already. Waiting for chrome store team to do the same. 😀

Edit: Published on Chrome Web Store as well. Cheers to a good day.
